services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AntroninConsulting\PswExpirationBundle\:
        resource: '../src/'
        exclude: '../src/Config/definition.php'

    AntroninConsulting\PswExpirationBundle\Security\PasswordExpirationChecker:
        bind:
            $passwordLifetime: '%psw_expiration.lifetime%'
            $warningThreshold: '%psw_expiration.warning_threshold%'
            $unit: '%psw_expiration.unit%'
